version: '3.9'

services:
  backnljinternal:
    image: back-nlj-internal
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - red-nlj-internal
    labels:
      - "traefik.http.routers.employees.rule=Host(`employees.localhost`)"
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    env_file:
      - .env    
networks:
  red-nlj-internal:
    external: true

