// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// Health is an autogenerated mock type for the Health type
type Health struct {
	mock.Mock
}

// Resource provides a mock function with given fields: g
func (_m *Health) Resource(g *echo.Group) {
	_m.Called(g)
}

// NewHealth creates a new instance of Health. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealth(t interface {
	mock.TestingT
	Cleanup(func())
}) *Health {
	mock := &Health{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
