// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/Shepherd-Go/Back-Nlj-Internal.git/dtos"
	mock "github.com/stretchr/testify/mock"
)

// ActivateEmail is an autogenerated mock type for the ActivateEmail type
type ActivateEmail struct {
	mock.Mock
}

// ActivateEmail provides a mock function with given fields: ctx, pass
func (_m *ActivateEmail) ActivateEmail(ctx context.Context, pass dtos.ActivateEmail) (dtos.EmployeeResponse, error) {
	ret := _m.Called(ctx, pass)

	if len(ret) == 0 {
		panic("no return value specified for ActivateEmail")
	}

	var r0 dtos.EmployeeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.ActivateEmail) (dtos.EmployeeResponse, error)); ok {
		return rf(ctx, pass)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.ActivateEmail) dtos.EmployeeResponse); ok {
		r0 = rf(ctx, pass)
	} else {
		r0 = ret.Get(0).(dtos.EmployeeResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.ActivateEmail) error); ok {
		r1 = rf(ctx, pass)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewActivateEmail creates a new instance of ActivateEmail. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivateEmail(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivateEmail {
	mock := &ActivateEmail{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
