// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/Shepherd-Go/Back-Nlj-Internal.git/dtos"
	mock "github.com/stretchr/testify/mock"
)

// LogIn is an autogenerated mock type for the LogIn type
type LogIn struct {
	mock.Mock
}

// SearchEmployeByEmailOrUsername provides a mock function with given fields: ctx, identifier
func (_m *LogIn) SearchEmployeByEmailOrUsername(ctx context.Context, identifier string) (dtos.Session, error) {
	ret := _m.Called(ctx, identifier)

	if len(ret) == 0 {
		panic("no return value specified for SearchEmployeByEmailOrUsername")
	}

	var r0 dtos.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dtos.Session, error)); ok {
		return rf(ctx, identifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dtos.Session); ok {
		r0 = rf(ctx, identifier)
	} else {
		r0 = ret.Get(0).(dtos.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, identifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLogIn creates a new instance of LogIn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogIn(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogIn {
	mock := &LogIn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
