// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LogsError is an autogenerated mock type for the LogsError type
type LogsError struct {
	mock.Mock
}

// InsertLogsError provides a mock function with given fields: LogsError
func (_m *LogsError) InsertLogsError(LogsError error) {
	_m.Called(LogsError)
}

// NewLogsError creates a new instance of LogsError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogsError(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogsError {
	mock := &LogsError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
