// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SendEmail is an autogenerated mock type for the SendEmail type
type SendEmail struct {
	mock.Mock
}

// EmployeeRegistered provides a mock function with given fields: email, first_name, username, password
func (_m *SendEmail) EmployeeRegistered(email string, first_name string, username string, password string) {
	_m.Called(email, first_name, username, password)
}

// ForgotPassword provides a mock function with given fields: email, pass
func (_m *SendEmail) ForgotPassword(email string, pass string) {
	_m.Called(email, pass)
}

// NewSendEmail creates a new instance of SendEmail. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSendEmail(t interface {
	mock.TestingT
	Cleanup(func())
}) *SendEmail {
	mock := &SendEmail{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
